export const ACCOUNT_ROUTE = '/account'
export const ADDRESS_ROUTE = '/account/addresses'
export const EXCHANGE_RATE_ROUTE = '/exchange_rate'
export const MY_ORDERS_ROUTE = '/order_requests'
export const SUPPORTED_MARKETS_ROUTE = '/supported_markets'
export const CRAWLER_SELECTORS_ROUTE = '/crawler_selectors'
export const BANK_ACCOUNTS_ROUTE = '/bank_accounts'
